site_name: Siddhi-Execution-Unique
extra_css:
- stylesheets/extra.css
extra_javascript:
- javascripts/extra.js
site_favicon: images/favicon.ico
extra:
  logo: images/siddhi-logo-w.svg
  palette:
    primary: teal
    accent: teal
google_analytics:
- UA-103065-28
- auto
pages:
- Welcome to WSO2 Siddhi Execution Unique: index.md
- API Docs:
  - 4.0.7: api/4.0.7.md
  - 4.0.8: api/4.0.8.md
- License: license.md
theme: material
